### ISSUE TITLE
civ 6 , cant use the editor, file isnt readable

### ISSUE THREAD

**Issue by edward1510** [bmaupin/react-civ5save#10]
google chrome  the newest one

 trying to edit a save file on civ 6 says my file isnt readable
#### Description

 arent using any
#### Mods

cant share the file

**Comment by bmaupin** [comment]
Unfortunately this application is only for Civilization 5. Civ 6 is a completely different game and the save files aren't compatible.

The CivFanatics forums are a great resource, I'd recommend asking there if there's something like this for Civ 6. Here's the link: https://forums.civfanatics.com

Hope that helps!
